
'Common dependencies':
  image: node:12.18.2
  stage: core-dependencies
  artifacts:
    paths:
      - packages/common/node_modules/
  dependencies: []
  script:
    - cd packages/common
    - npm install
#  only:
#    changes:
#      - packages/common/**/*
#      - .gitlab-ci.yml

'Common build':
  image: node:12.18.2
  stage: core-build
  artifacts:
    paths:
      - packages/common/dist/
  dependencies:
    - 'Common dependencies'
  script:
    - cd packages/common
    - npm run build
#  only:
#    changes:
#      - packages/common/**/*
#      - .gitlab-ci.yml

'Common publishing': 
  image: node:12.18.2
  stage: core-publishing
  dependencies:
    - 'Common build'
  script:
    - cd packages/common
    - npm version patch
    - echo "
      @ArcaneDiver:registry=https://gitlab.com/api/v4/packages/npm/\n

      //gitlab.com/api/v4/packages/npm/:_authToken=${NPM_TOKEN}\n
      //gitlab.com/api/v4/projects/19750243/packages/npm/:_authToken=${NPM_TOKEN}\n
      " >> .npmrc
    - npm publish --loglevel verbose